baseURL = "https://mishalmsb.github.io/"
languageCode = "en-us"
title = "Mishal | Front-end web developer"
description = "Mishal | Front-end web developer"
theme = "version-1"

[params]
inConstruction = true

  [params.preloader]
  enable = true
  preloader = "images/preloader.gif"

  [params.internalPlugins]
  css = [ ]

    [[params.internalPlugins.js]]
    link = "js/helpers.js"

    [[params.internalPlugins.js]]
    link = "js/text-rotate.js"

    [[params.internalPlugins.js]]
    link = "js/text-rotate.js"

[params.devPlugins.internalPlugins]
css = [ ]

  [[params.devPlugins.internalPlugins.js]]
  link = "js/particles.js"

[params.devPlugins.externalPlugins]
css = [ ]

  [[params.devPlugins.externalPlugins.js]]
  link = "plugins/particles/particles.min.js"

  [params.externalPlugins]
  css = [ ]

    [[params.externalPlugins.js]]
    link = "plugins/bootstrap/js/bootstrap.min.js"

